### ISSUE TITLE
Cyrillic symbols with server side rendering

### ISSUE THREAD

**Issue by tgladyshev** [swaechter/angularj-universal#13]
With server side rendering all cyrillic characters in generated html are replaced with "?" At the same time, client-side rendering characters are displayed correctly. Any idea why this happens?

Windows 7

``<dependency>``
           `` <groupId>com.eclipsesource.j2v8</groupId>``
             ``<artifactId>j2v8_win32_x86</artifactId> ``
           ``  <version>4.6.0</version> ``
 ``</dependency> ``

 ``<dependency> ``
           ``  <groupId>ch.swaechter</groupId> ``
  ``           <artifactId>angularj-universal-renderer-v8</artifactId> ``
        ``     <version>0.0.1</version> ``
 ``</dependency> ``

**Comment by swaechter** [comment]
Hey, is it possible for you to publish a small example where I am able to reproduce the problem?

Also I should release a 0.0.2 with the latest changes.

**Comment by tgladyshev** [comment]
Sorry for the long answer. All ok, it was my fault.

**Comment by swaechter** [comment]
No problem, I was also able to reproduce the problem. For safety, I added a charset attribute in the configuration. For more information see commit 16623b08f51816a1669ce1ebbb96be15d607d7e8 or the README.me I am going to update soon.
