### ISSUE TITLE
Release 0.0.2

### ISSUE THREAD

**Issue by MarkVink** [swaechter/angularj-universal#15]
Hey,

Would it be possible to build and push a 0.0.2 release to Maven?
I would like to be able to use the 'Make it possible to use several render engines in parallel' commit.

**Comment by swaechter** [comment]
Hi Mark

I just released version 0.0.2. For more information see the CHANGELOG.md or repo2.maven.org/maven2/ch/swaechter  . In case you are doing some performance tests/benchmarks, I would be really interested in them.

I am going to close this issue.

**Comment by MarkVink** [comment]
I noticed, thank you!
