### ISSUE TITLE
bug: Please delete temp files

### ISSUE THREAD

**Issue by 4garfield** [swaechter/angularj-universal#17]
Hi

currently the `ResourceProvider` API would create temp `server.bundle.js` in user temp folder, but the code never clean the temp folders, see `getServerBundle` function in `ResourceProvider` class.

is it reasonable, can add delete method ?

**Comment by swaechter** [comment]
Hi there

Indeed, I just fixed this with commit 0bd2827fafed75c8261d5dbc73841f7611c4a8c4 . The file now will be deleted after the JVM has finished.

Side note: The Java part of J2V8 will download a C/C++ JNI library that provides the wrapper methods to the NodeJS runtime. This library is by default saved in the home directory, sadly not the most elegant way. I hope that this review request will be merged, so we are also able to choose the location (The library won't be deleted after JVM exit): https://github.com/eclipsesource/J2V8/pull/346/

I will close the issue. If you encounter any issues, feel free to reopen it. I hope I am able to release a v0.0.2 version this week/next week.

**Comment by swaechter** [comment]
I just released 0.0.2 with your fix.
