### ISSUE TITLE
Once the project is imported, how can I run it?

### ISSUE THREAD

**Issue by csiegmundt** [swaechter/angularj-universal#18]
What are the steps necessary to run the project after pulling it?

**Comment by swaechter** [comment]
Hey

There are two possible ways:

1.) From the command line

    git clone https://github.com/swaechter/angularj-universal
    cd angularj-universal
    mvn package
    java -jar angularj-universal-example-spring-boot/target/angularj-universal-example-spring-boot-0.0.2.jar

2.) From an IDE

    Import the project
    Execute an `npm install` and `npm build` in angularj-universal-application/src/main/angular
     angularj-universal-example-spring-
    boot/src/main/java/ch/swaechter/angularjuniversal/example/springboot/WebApplication.java
     (After changes in your Angular application, rerun npm build

**Comment by parthbulusu** [comment]
The steps are not working for me, "Mvn package" is failing checking some test assertions, even when I comment the unit test which are failing I cannot get the tomcat server to start up.

**Comment by swaechter** [comment]
It looks like the separator `;` is in the NPM scripts not working on Windows, so I had to replace them with a `&&` and it should work now.

If you encounter any further issues, feel free to reopen the issue
