### ISSUE TITLE
How to use Angular Universal with Spring Backend

### ISSUE THREAD

**Issue by vxhviet** [swaechter/angularj-universal#24]
Hi,

First of all, thank you for the tremendous effort you've put into this lib and please forgive me if my question is inappropriate as I mainly focus on the implementation detail of [this issue](https://github.com/angular/universal/issues/1000). 

I don't have much experience with front-end development as I'm mainly an Android developer, just side track into front-end to help develop an ad landing page for our app so a lot of these stuff is very new to me. We have just finished a basic Angular app and then got hit with this performance issue, very long load time on mobile device (~10ms) for the first page. I investigate a little bit and then came across Angular Universal, but the problem is our backend is in Java/ Spring so I would need to use the mentioned issue-1000 workaround. 

I followed the main tutorial and got stuck at this step:

[universal-web-server](https://angular.io/guide/universal#universal-web-server)

which is an example for Node Express server.

I kind of have a rough idea of putting the Usage Server section:

```javascript
const socketEngine = require('@nguniversal/socket-engine');

// * NOTE :: leave this as require() since this file is built Dynamically from webpack
const {AppServerModuleNgFactory, LAZY_MODULE_MAP} = require('./dist/server/main');

socketEngine.startSocketEngine(AppServerModuleNgFactory);
```

into the `server.ts` file.

And the Usage Client would somehow go into our Java backend.

If you don't mind would you please explain how could I do that in a noob-friendly way? :)

**Comment by Nivani** [comment]
For your client in Java Spring, this might help: https://stackoverflow.com/questions/27765044/how-to-implement-spring-support-for-custom-template-engine

The "Usage Client" code will go into the render method of your custom implementation of org.springframework.web.servlet.View. The html response from the universal server should be written to the output stream of Spring's respone object (response.getOutputStream()).

**Comment by vxhviet** [comment]
Thank you for your response, I'll try to implement as your suggestion.

**Comment by Nivani** [comment]
No problem. Please share your findings, I'm curious to know if that works well.

**Comment by swaechter** [comment]
I finally wrote an experimental version that uses `socketEngine.startSocketEngine` via a TCP connection on port 9090. Feel free to give it a try :)
