### ISSUE TITLE
Unable to start spring boot with angularj-universal "window is not defined"

### ISSUE THREAD

**Issue by jesus-dayo** [swaechter/angularj-universal#26]
Hi ,

Tried integrating the tutorial you made in my existing spring boot application, however unable to start it with the following error:
![image](https://user-images.githubusercontent.com/9920580/43678566-236ea63e-9848-11e8-8f38-4c014815423c.png)

**Comment by swaechter** [comment]
Hey

From the universal chapter of the official Angular documentation: https://angular.io/guide/universal#working-around-the-browser-apis:

> Because a Universal platform-server app doesn't execute in the browser, you may have to work around some of the browser APIs and capabilities that are missing on the server.
> 
> You won't be able reference browser-only native objects such as window, document, navigator or location. If you don't need them on the server-rendered page, side-step them with conditional logic.
> 
> Alternatively, look for an injectable Angular abstraction over the object you need such as Location or Document; it may substitute adequately for the specific API that you're calling. If Angular doesn't provide it, you may be able to write your own abstraction that delegates to the browser API while in the browser and to a satisfactory alternative implementation while on the server.
> 
> Without mouse or keyboard events, a universal app can't rely on a user clicking a button to show a component. A universal app should determine what to render based solely on the incoming client request. This is a good argument for making the app routeable.
> 
> Because the user of a server-rendered page can't do much more than click links, you should swap in the real client app as quickly as possible for a proper interactive experience.

So more or less you or a third party (like for example jQuery etc.) are accessing the `window` object that doesn't exist on the server side. What you can do:

* In case it is your code, do a check and don't execute it. There is a way to detect if your code is running in the browser or on the server side: https://stackoverflow.com/questions/46099644/how-to-check-for-isbrowser-in-angular-4
* In case it is your code, write an abstraction that can be injected via dependency injection and that doesn't rely on the `window` object
* In case of a third party library: Tricky....try to opt it out on the server side or search for an alternative that doesn't rely on `window`

In case you aren't accessing `window` by yourself, search for it in the server bundle and maybe you'll find out to with third party library it does belong?
