### ISSUE TITLE
Rendering takes too long

### ISSUE THREAD

**Issue by RadouaneRoufid** [swaechter/angularj-universal#27]
Hi, 

I would like to start with great thanks for your wonderful work. 

I have a angular app with a Spring boot backend. I use your solution to implement SSR. The solution works great, but the first load takes about 1 minute. I don't really understand why.

On server start up, I have the following warning ; 
```
Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /home/me/libj2v8_linux_x86_64.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
```

And the following logs when I try to reach "/".

```
[Error]
ERROR [Error]
ERROR [Error]
```

Any explanation of why my rendering takes too long ?

Thank you.

**Comment by swaechter** [comment]
Hey Radouane

The very first time the J2V8 render is started, it will download the J2V8 DLL and place it in your home directory -after that it will just look for the DLL and use it. Is this DLL somehow deleted from time to time, e.g. anti virus software?

If not, can you share a reproducible example (Git repo) + information about your system (OS etc) so I can try to reproduce the problem?

Best,
Simon

**Comment by RadouaneRoufid** [comment]
Thank you. I will check that and share a reproducible repo.

**Comment by RadouaneRoufid** [comment]
A simple angular app works fine with ssr. I will try to add some complexity to reproduce my problem.

**Comment by RadouaneRoufid** [comment]
The problem was due to ifvisible. Putting it likle below solved the issue : 
```

 if (isPlatformBrowser(this.platformId)) {
            ifvisible.on('wakeup', () => {
                this.countConversation();
            });
        }
```

**Comment by swaechter** [comment]
Yeah that make sense, because the "screen visible" event will never occur. But still it's strange that registering the listener works at all (Because there is no client DOM)

**Comment by RadouaneRoufid** [comment]
I'm using domino to fake DOM. It can explain why the listener worked.
