### ISSUE TITLE
angular 8 not working

### ISSUE THREAD

**Issue by ferinoc** [swaechter/angularj-universal#32]
Hi,

after we migrated to angular 8, we can't start java application. We have this errors message:

node.js:376
        callback();
        ^
undefined:8: SyntaxError: Unexpected token {

This error only occurs when we start the java application with angular-universal activated.
Project is build without problems.

Do you have idea how to fix it? 
Thank you.

` "dependencies": {
    "@angular/animations": "8.2.0",
    "@angular/common": "8.2.0",
    "@angular/compiler": "8.2.0",
    "@angular/core": "8.2.0",
    "@angular/forms": "8.2.0",
    "@angular/platform-browser": "8.2.0",
    "@angular/platform-browser-dynamic": "8.2.0",
    "@angular/platform-server": "8.2.0",
    "@angular/router": "8.2.0",
    "@nguniversal/common": "^8.1.1",
    "@nguniversal/module-map-ngfactory-loader": "^8.1.1",
    "@nguniversal/socket-engine": "^8.1.1",
    "@ngx-translate/core": "^11.0.1",
    "classlist.js": "^1.1.20150312",
    "copy": "^0.3.2",
    "core-js": "^2.6.5",
    "del-cli": "^1.1.0",
    "localize-router": "^2.0.0-RC.2",
    "localize-router-http-loader": "^1.0.2",
    "npm": "^6.9.0",
    "prettier": "^1.17.0",
    "rxjs": "^6.4.0",
    "svgxuse": "^1.2.6",
    "tslib": "^1.9.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.802.0",
    "@angular/cli": "8.2.0",
    "@angular/compiler-cli": "8.2.0",
    "@angular/language-service": "8.2.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "^2.0.6",
    "@types/node": "^6.14.4",
    "codelyzer": "^5.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "json-server": "^0.14.2",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.4.3",
    "karma-jasmine": "^1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^6.0.0",
    "svg-sprite": "^1.5.0",
    "ts-loader": "^6.0.4",
    "ts-node": "3.x",
    "tslint": "^5.16.0",
    "typescript": "3.5.3",
    "uglifyjs-webpack-plugin": "^2.1.2",
    "webfont": "^8.2.1",
    "webpack-cli": "^3.3.7"
  }`

**Comment by swaechter** [comment]
Hey the project has some complexity, so can you provide a minimal reproducible project as Github project?

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by jayserdny** [comment]
I am also facing the issue with Angular 8. It is a brand new project.

**Comment by swaechter** [comment]
@jayserdny Can you share a working Git project, so I can just git clone npm install/build + maven/gradle build & run it? At the moment I am really short on time + preparing my vacations

**Comment by jayserdny** [comment]
@swaechter I will create a sample repo soon. Right now the git project is not in Github.

**Comment by ARadauer** [comment]
imho this is a J2V8 issue https://github.com/eclipsesource/J2V8/issues/217
but I haven't found a solution yet

**Comment by swaechter** [comment]
@ARadauer Thanks for the information, I wasn't aware of the fact that J2V8 refocuses on a Javascript engine only. I guess it's really time consuming and difficult to keep up with all the different platforms & requirements. Looks like the TCP/gRPC approach is really the future.
