### ISSUE TITLE
This is still alive

### ISSUE THREAD

**Issue by lilletech** [swaechter/angularj-universal#38]
Does this project does have a future?
What about grpc?

**Comment by swaechter** [comment]
Hey Jimmy, yes and no:

No: This project started when SSR wasn't that easy and required a lot of boilerplate code (Like a custom communication between Java and Node.js. There was no TCP/gRPC engine). At that time I started I used J2V8 Java Node.js bindings.

In addition SSR can become quite complex (How to handle cookies? local storage replacement? Security?). For more information take a look at this thread I opened: https://github.com/angular/angular/issues/22443

Yes: On the other hand, Angular Universal improved a lot (I just didn't have the time to catch up). So personally I would setup and run a standalone Node.js instance & just write a custom TCP/gRPC class that calls this Node.js instance. A lot of my boilerplate code isn't required anymore.

With what background are you asking? Java application? Spring Boot?

Best,
Simon

**Comment by lilletech** [comment]
Thank you for your quick response.

I've coded many applications with Angular that didn't require SEO.

But now i develop an ecommerce application that, effectively, interacts with a spring boot rest application (maybe on quarkus later) that will need it. 

i'm currently searching for a rapid and easy solution. I currently use Angular 9 with angular material, spring-boot 2.3.0.M4

**Comment by dongmei-cao** [comment]
@swaechter Do you have any plan to support Angular 9 and Spring boot 2.3.0 soon?

**Comment by swaechter** [comment]
@dongmei-cao No, not at the moment. Updating the Spring Boot starter should be easy, but getting up to date with Angular universal & updating all examples etc. will take more time. In case you are running it with the latest Angular Universal and Spring Boot version I am looking for an updated version of my example app (Pull requests welcomed)
