### ISSUE TITLE
Fix the server and client transition

### ISSUE THREAD

**Issue by swaechter** [swaechter/angularj-universal#8]
At the moment the transition from the server side rendered page to the client side page is not working. I am not sure if preboot.js is already integrated into Angular CLI 1.3.0, so I have to verify that first.

If you have a working server side/client side transition with Angular CLI 1.3.0 and Node.js, please post a link to the project (Reference).

**Comment by kweheliye** [comment]
Hi,

Thanks so much for providing this library to enable Angular Universal with Java back end.

I have followed your instructions and I was able to run your the demo-app.
Below is my pom.xml set up. that should solve the issue

             ```
             <dependency>
			<groupId>ch.swaechter</groupId>
			<artifactId>angularj-universal-renderer-v8</artifactId>
			<version>0.0.1</version>
		</dependency>
		<dependency>
			<groupId>ch.swaechter</groupId>
			<artifactId>angularj-universal-renderer</artifactId>
			<version>0.0.1</version>
		</dependency>

```

**Comment by swaechter** [comment]
I updated the application and fixed the server to client transition with commit a86893e997a0e88aaa1d42b97110c80eb061c80f. We now have a working transition and have some kind of feature parity with the Express.js implementation (Except caching).

@kweheliye You posted on this issue but deleted your answer. Can you test the latest version again?
